// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://bkrmvjavqdnbsbfrrkyq.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImJrcm12amF2cWRuYnNiZnJya3lxIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDg0NzQ3NDUsImV4cCI6MjA2NDA1MDc0NX0.OMQ_alDBJslgJcZ1G3x9_GZsEfO1w_apbXB-RZZxj74";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);